- src/args.rs
- src/main.rs
- src/oapi.rs
Ability to filter resources through:
- tag key
- tag value
- tag key=value
Closes #29
> Add filtering for resources

- src/main.rs
> Exit when there is an error while fetching resources

- Cargo.lock
- src/core.rs
- src/main.rs
`main.rs` refactoring with more idiomatic rust code.
just a quick reformatting on `core.rs` for now another PR will follow with immutable resources computation (so please keep focus on main for now).
> Quick idiomatic refactoring on main.rs

- docs/README.md
- src/core.rs
- src/core/flexible_gpus.rs
- src/core/load_balancers.rs
- src/core/vpn.rs
- src/main.rs
- src/oapi.rs
- src/oapi/flexible_gpus.rs
- src/oapi/load_balancers.rs
- src/oapi/vpn.rs
- Flexible Gpus
- Load Balancers
- VPN
Ref #47
> Add more IaaS resources

- src/core.rs
- src/core/nat_services.rs
- src/core/public_ips.rs
- src/core/snapshots.rs
- src/core/vms.rs
- src/core/volumes.rs
- src/oapi.rs
- src/oapi/nat_services.rs
- src/oapi/public_ips.rs
- src/oapi/snapshots.rs
- src/oapi/vms.rs
- src/oapi/volumes.rs
Refactor to use submodule instead of one big module
> Refactor oapi and core

- src/core/vms.rs
- src/oapi/vms.rs
> Rename product to license

- src/core/vms.rs
- src/oapi/vms.rs
> Add product_codes in the VM resources

- .github/workflows/pull-request.yml
- src/core/oos.rs
- src/oapi.rs
- src/oapi/vms.rs
- src/ods/error.rs
- src/ods/ser.rs
For the CI, use the flags as [official website](https://doc.rust-lang.org/nightly/clippy/continuous_integration/github_actions.html)
> Fix clippy warnings

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/core.rs
- src/main.rs
- src/ods/ser.rs
- src/prometheus/error.rs
- src/prometheus/mod.rs
- src/prometheus/ser.rs
This PR adds prometheus format output using serde format.
Closes https://github.com/outscale/osc-cost/issues/6
> Add serde prometheus

- Cargo.toml
This PR is to update metdata for the package. The github action is already commited.
Closes #35
> Add some information for publishing the project on crates

- docs/README.md
- helm/Dockerfile
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- helm/osccost/values.yaml
Prepare docs, helm charts and dockerfile for the futur release 0.2.0.
> Prepare docker and helm for the futur release 0.2.0

- helm/Dockerfile
- helm/entrypoint.sh
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- helm/osccost/templates/deployment.yaml
- helm/osccost/templates/secret.yaml
- helm/osccost/values.yaml
Add some improvements using helm chart.
Allow to pass parameters to command (especially `--skip-resource Oos`)
> Improve helm and allow some parameters in command line

- Cargo.lock
- Cargo.toml
- Makefile
- docs/CONTRIBUTING.md
- helm/Dockerfile
- helm/entrypoint.sh
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- helm/osccost/values.yaml
Prepare next release v0.3.2 and use docker buildx and helm-docs
> Feat: Prepare next release v0.3.2 and use docker buildx and helm-docs

- Cargo.lock
- Cargo.toml
- helm/Dockerfile
- helm/osccost/README.md
- helm/osccost/values.yaml
> Support Old Glibc

- helm/Dockerfile
> Unfix package

- Cargo.lock
- Cargo.toml
- helm/Dockerfile
- helm/osccost/README.md
- helm/osccost/values.yaml
- int-tests/run.sh
Change netcat package and release
> Change netcat package and release

- helm/docker-compose.yaml
- helm/prometheus.yml
Enable to test prometheus exporter with docker-compose
> Enable to test prometheus exporter with docker-compose

- src/oapi.rs
- src/oapi/flexible_gpus.rs
- src/oapi/load_balancers.rs
- src/oapi/nat_services.rs
- src/oapi/public_ips.rs
- src/oapi/snapshots.rs
- src/oapi/vms.rs
- src/oapi/volumes.rs
- src/oapi/vpn.rs
Get response trace
Closes #131
> Get response trace

- src/oapi.rs
- src/oapi/flexible_gpus.rs
- src/oapi/load_balancers.rs
- src/oapi/nat_services.rs
- src/oapi/public_ips.rs
- src/oapi/snapshots.rs
- src/oapi/vms.rs
- src/oapi/volumes.rs
- src/oapi/vpn.rs
Swicth log level to debug for response
> Swicth log level to debug for response

- Cargo.lock
- Cargo.toml
- docs/README.md
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- helm/osccost/values.yaml
- src/core.rs
- src/core/dedicated_instances.rs
- src/core/vms.rs
- src/oapi.rs
- src/oapi/dedicated_instances.rs
- src/oapi/vms.rs
- src/output/prometheus/mod.rs
Calculate dedicated instance and add tag tenancy and nested_virtualization
Closes #123
> Calculate dedicated instance

- Cargo.lock
- Cargo.toml
- docs/README.md
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- src/oapi/vms.rs
Fix bad calculation of dediacted vm
> Fix bad calculation of dediacted vm

- helm/osccost/values.yaml
Update image version with the release
> Update image version

- Cargo.lock
- Cargo.toml
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- helm/osccost/values.yaml
- src/oapi/vms.rs
> Fix helm relase and set explicit name

- src/oapi/vms.rs
> Fix box VM type price computation

- helm/osccost/templates/deployment.yaml
- helm/osccost/values.yaml
We can now really set readOnlyRootFilesystem to true :)
> Ability to set readOnlyRootFilesystem to true

- Cargo.lock
- Cargo.toml
- helm/osccost/Chart.yaml
- helm/osccost/README.md
- helm/osccost/values.yaml
preparation for release v0.5.4
Please check the relevant option(s):
Please describe the test strategy:
Add any additional context or screenshots if necessary.
> 🔖 release: release v0.5.4

- .github/workflows/publish.yml
add trusted publisher to workflow
Please check the relevant option(s):
Please describe the test strategy:
> 👷 ci: add trusted publisher to workflow

- .github/actions/install_toolchain/action.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
Please include a summary of the changes and the related context. If this is a feature, explain the motivation. If it's a bug fix, describe what was broken.
Fixes: #<issue-number> _(if applicable)_
Please check the relevant option(s):
Please describe the test strategy:
Commands used (if applicable):
```bash
my-cli-tool build --verbose
my-cli-tool test
````
Add any additional context or screenshots if necessary.
> 💚 ci: fix toolchain setup
